### ISSUE TITLE
packages are incompatible

### ISSUE THREAD

**Issue by Alpslee** [yixuanhuang98/Points2Plans#1]
The following packages are incompatible
├─ cryptography ==38.0.1 py38h9ce1e76_0 is installable and it requires
│  └─ openssl <1.1.2a , which can be installed;
└─ openssl ==3.1.0 h0b41bf4_0 is not installable because it conflicts with any installable versions previously reported.

I run it on ubuntu 22 cuda 12,any suggestions? thanks

**Comment by yixuanhuang98** [comment]
You can remove the "cryptography" package from the conda_env.yml file, as it may cause incompatible issues.

**Comment by j-jeanchok** [comment]
我请问一下，我运行LLM时会卡在那里没输出，但我可以在终端ping上openai
